version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.2.1-browsers
        environment:
          TZ: "/usr/share/zoneinfo/Europe/London"
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10.2.1-browsers
        environment:
          TZ: "/usr/share/zoneinfo/Europe/London"
    steps:
      - checkout
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn semantic-release

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
