version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: sudo cp /usr/share/zoneinfo/Europe/London /etc/localtime
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn eslint
      - run: yarn test:coverage
  deploy:
    docker:
      - image: circleci/node:8.9.1-browsers
    steps:
      - checkout
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run semantic-release || true

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master